syntax off
set lazyredraw
set nocompatible
set nowrap
set showmatch
set wildmenu
set modelines=0
set autoread


" tabs spaces
autocmd BufRead *.yml,*.yml.*,*.yaml    setlocal shiftwidth=2 tabstop=2 expandtab
autocmd BufRead *.js                    setlocal shiftwidth=2 tabstop=2 expandtab
autocmd BufRead *.py,*.sh,*.txt         setlocal shiftwidth=4 tabstop=4 expandtab
autocmd BufRead *.html                  setlocal shiftwidth=2 tabstop=2 expandtab
autocmd BufRead *.rb                    setlocal shiftwidth=2 tabstop=2 expandtab
set tabstop=4 shiftwidth=4 expandtab


" split
set fillchars=stl:-
set fillchars+=stlnc:-
set fillchars+=vert:\|
highlight StatusLine   ctermfg=None cterm=None
highlight StatusLineNC ctermfg=Gray cterm=None
highlight VertSplit    ctermfg=None cterm=None


set nobackup
set nowritebackup


" search
set ignorecase
set hlsearch
highlight Search ctermbg=3
nnoremap <esc><esc> :silent! nohlsearch<cr>


" visual higlight
highlight Visual ctermfg=Black
highlight Visual ctermbg=3


" fix copy pasting
set paste
" sudo apt get install vim-gtk
" vim --version | grep clipboard
set clipboard=unnamedplus
function! ClipboardYank()
  call system('xclip -i -selection clipboard', @@)
endfunction
function! ClipboardPaste()
  let @@ = system('xclip -o -selection clipboard')
endfunction
vnoremap <silent> y y:call ClipboardYank()<cr>
vnoremap <silent> d d:call ClipboardYank()<cr>
nnoremap <silent> p :call ClipboardPaste()<cr>p


" eol char and color
"set listchars=eol:¬
"highlight NonText ctermfg=Gray


" 80 columns rule
"highlight ColorColumn ctermbg=58
highlight ColorColumn ctermbg=3
highlight ColorColumn ctermfg=Black
call matchadd('ColorColumn', '\%81v', 100)


" remove trailing whitespace
" autocmd BufWritePre * %s/\s\+$//e


" typewriter scroll
"set scrolloff=999


" distraction free
highlight FoldColumn ctermbg=none
"set foldcolumn=12


" command mode
nnoremap ; :
nnoremap : ;


" line number
"set number relativenumber
highlight LineNr ctermfg=DarkGrey
"highlight CursorLineNr ctermfg=DarkGrey

"augroup numbertoggle
"  autocmd!
"  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
"  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
"augroup END


" find
set path+=**


" netrw
let g:netrw_banner=0
let g:netrw_liststyle = 3
let g:netrw_winsize = 30
let g:netrw_browse_split = 4


"tab
highlight TabLineFill cterm=none ctermbg=none
highlight TabLine cterm=none ctermfg=darkgrey ctermbg=none


" ripgrep
" sudo apt install ripgrep
if executable("rg")
  set grepprg=rg\ --vimgrep\ --no-heading
endif


" show quickfix after grep
augroup grep_quickfix
    autocmd!
    autocmd QuickFixCmdPost [^l]* cwindow
    autocmd QuickFixCmdPost l*    lwindow
augroup END


" bind K to grep word under cursor
nnoremap K :grep! "\b<C-R><C-W>\b"<CR>:cw<CR>


" backspace fix
set backspace=indent,eol,start


" keep selection in visualblock
vnoremap < <gv
vnoremap > >gv


set swapfile
set dir=/tmp


" disable start message
set shortmess=I
