---
- name: provision
  hosts: localhost
  connection: local
  gather_facts: False

  vars_prompt:
  - name: hostname
    prompt: hostname
    private: no
  - name: ansible_user
    prompt: ansible_user
    private: no
  - name: ansible_sudo_pass
    prompt: ansible_sudo_pass

  tasks:
  - name: set hostname
    command: echo "{{ hostname }}" > /etc/hostname
    become: yes

  - name: remove packages
    apt:
      name: "{{ packages }}"
      state: absent
      autoremove: yes
      purge: yes
    vars:
      packages:
      - libreoffice*
      - qcomicbook
      - gnome-contacts
      - simple-scan
      - geary
      - gnome-weather
      - totem*
      - evince
      - eog
      - yelp
    ignore_errors: yes
    become: yes

  - name: delete folders
    file:
      path: ~/{{ item }}
      state: absent
    with_items:
      - Documents
      - Downloads
      - Desktop
      - Music
      - Pictures
      - Public
      - Templates
      - Videos

  # TODO: separate programs with external inputs ala qubes
  - name: install development tools
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - git
      - tig
      - vim
      - tmux
      - xclip
      - htop
      - ncdu
      - aria2
      - pass
      - mpv
      - zathura
      - pinentry-tty
      - curl
      - openvpn
      - sxiv
      - pv
      - jq
      - maim
      - oathtool
      - xdotool
      - pigz
    become: yes

  - name: set pinentry /usr/bin/pinentry-tty
    command: update-alternatives --set pinentry /usr/bin/pinentry-tty
    become: yes

  # TODO
  - name: install stubby
    apt:
      name: stubby
    become: yes

  - name: stop cups service
    systemd:
      name: "{{ item }}"
      state: stopped
    with_items:
      - cups
      - cups-browsed
    become: yes

  - name: disable cups service
    systemd:
      name: "{{ item }}"
      enabled: no
    with_items:
      - cups
      - cups-browsed
    become: yes

  # TODO: popos specific
  - name: do not start appcenter
    shell: |
      cd /etc/xdg/autostart
      mv io.elementary.appcenter-daemon.desktop io.elementary.appcenter-daemon.desktop.bak
    ignore_errors: yes
    become: yes

  - name: disable background
    shell: |
      gsettings set org.gnome.desktop.interface enable-animations false

  - name: set solid wallpaper
    shell: |
      gsettings set org.gnome.desktop.background picture-options 'none'
      gsettings set org.gnome.desktop.background primary-color '#000000'

  - name: remove splash in boot and disable ipv6 and intel_pstate
    replace:
      path: "{{ item.path }}"
      regexp: "{{ item.regexp1 }}"
      replace: "{{ item.replace }}"
    with_items:
      - { path: '/boot/efi/loader/entries/Pop_OS-current.conf', regexp1: 'quiet', replace: ''}
      - { path: '/boot/efi/loader/entries/Pop_OS-current.conf', regexp1: 'splash', replace: 'intel_pstate=disable ipv6.disable=1'}
    become: yes

  - name: clone dotfiles
    git:
      repo: "https://github.com/janmaghuyop/{{ item }}.git"
      dest: "/home/{{ ansible_user }}/{{ item }}"
      clone: yes
    with_items:
      - dotfiles
      - bin
    ignore_errors: yes

  - name: set dotfiles
    shell: |
      cd /home/{{ ansible_user }}
      cd dotfiles
      ./link.sh
      git remote rm origin
      git remote add origin git@github.com:janmaghuyop/dotfiles.git
      cd ..
      cd bin
      git remote rm origin
      git remote add origin git@github.com:janmaghuyop/bin.git
