---
- name: provision
  hosts: localhost
  connection: local
  gather_facts: False

  vars_prompt:
  - name: hostname
    prompt: hostname
    private: no
  - name: ansible_user
    prompt: ansible_user
    private: no
  - name: ansible_sudo_pass
    prompt: ansible_sudo_pass

  tasks:

  # offline

  - name: remove packages
    apt:
      name: "{{ packages }}"
      state: absent
      autoremove: yes
      purge: yes
    vars:
      packages:
      - libreoffice*
      - qcomicbook
      - gnome-contacts
      - simple-scan
      - geary
      - gnome-weather
      - totem*
      - evince
      - eog
      - yelp
    ignore_errors: yes
    become: yes

  - name: delete folders
    file:
      path: ~/{{ item }}
      state: absent
    with_items:
      - Documents
      - Downloads
      - Desktop
      - Music
      - Pictures
      - Public
      - Templates
      - Videos

  - name: stop cups service
    systemd:
      name: "{{ item }}"
      state: stopped
    with_items:
      - cups
      - cups-browsed
    become: yes

  - name: set git author
    shell: |
      git config --global user.email "janmaghuyop@pm.me"
      git config --global user.name "janmaghuyop"

  # popos specific

  - name: configure theme
    shell: |
      gsettings set org.gnome.desktop.interface enable-animations false

      # set solid wallpaper
      gsettings set org.gnome.desktop.background picture-options 'none'
      gsettings set org.gnome.desktop.background primary-color '#000000'

      # disable lock
      gsettings set org.gnome.desktop.screensaver lock-enabled false

      # remove favorites
      gsettings set org.gnome.shell favorite-apps []

      # enable hint
      gsettings set org.gnome.shell.extensions.pop-shell active-hint true

      # disable recent files
      gsettings set org.gnome.desktop.privacy remember-recent-files false

      # hide desktop icons
      gnome-extensions disable ding@rastersoft.com

      # hide workspace
      gnome-extensions disable always-show-workspaces@system76.com

      # only switch in current workspace
      gsettings set org.gnome.shell.app-switcher current-workspace-only true

  - name: remove shadow in dark and light theme
    shell: |
      sed -i "s/.*shadow.*//" /usr/share/gnome-shell/extensions/pop-shell@system76.com/dark.css
      sed -i "s/.*shadow.*//" /usr/share/gnome-shell/extensions/pop-shell@system76.com/light.css
    become: yes

  - name: disable shadow in window decoration
    lineinfile:
      dest: "/usr/share/gnome-shell/extensions/pop-shell@system76.com/{{ item }}.css"
      line: 'decoration {box-shadow: none;}'
    with_items:
      - dark
      - light
    become: yes

  - name: remove splash in boot and disable ipv6 and intel_pstate
    replace:
      path: "{{ item.path }}"
      regexp: "{{ item.regexp1 }}"
      replace: "{{ item.replace }}"
    with_items:
      - { path: '/boot/efi/loader/entries/Pop_OS-current.conf', regexp1: 'quiet', replace: ''}
      - { path: '/boot/efi/loader/entries/Pop_OS-current.conf', regexp1: 'splash', replace: 'intel_pstate=disable ipv6.disable=1'}
    become: yes

  - name: enable autologin
    lineinfile:
      dest: /etc/gdm3/custom.conf
      regex: '^#\s*{{ item.regex }}(.*)$'
      line: '{{ item.line }}'
    loop:
      - regex: 'AutomaticLoginEnable'
        line: 'AutomaticLoginEnable = true'
      - regex: 'AutomaticLogin'
        line: "AutomaticLogin = {{ ansible_user }}"
    become: yes

  - name: set host in hostnamectl
    command: hostnamectl set-hostname "{{ hostname }}"
    become: yes

  - name: replace hostname in hosts file
    replace:
      path: /etc/hosts
      regexp: "pop-os"
      replace: "{{ hostname }}"
    become: yes

  # online

  - name: install development tools
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - git
      - tig
      - vim
      - tmux
      - xclip
      - htop
      - ncdu
      - aria2
      - curl
      - lm-sensors
      - xdotool
      - pass
      - zathura
      - pinentry-tty
      - oathtool
      - sxiv
      - pv
      - jq
      - mpv
      - openvpn
      - maim
      - pigz
      - cmus
    become: yes

  - name: set pinentry /usr/bin/pinentry-tty
    command: update-alternatives --set pinentry /usr/bin/pinentry-tty
    become: yes

  - name: install stubby
    apt:
      name: stubby
    become: yes

  - name: install gnome extensions
    apt:
      name: "{{ packages }}"
    vars:
      packages:
      - gnome-shell-extension-autohidetopbar
    become: yes

  - name: disable connectivity checking
    shell: |
      apt-get install -y crudini
      crudini --set /var/lib/NetworkManager/NetworkManager-intern.conf "connectivity" ".set.enabled" "false"
    become: yes

  # https://support.system76.com/articles/battery/
  # https://linrunner.de/tlp/
  - name: install tlp to prolong battery life
    apt:
      name: "{{ packages }}"
      install_recommends: no
    vars:
      packages:
      - tlp
      - tlp-rdw
    become: yes

